### PR TITLE
Add 'disabled' state to rule list

### PR DESCRIPTION
**Pull request by bnichs**
Adds a "disabled" string to filter rule entries.

### CODE REVIEW

**Comment by tien** [comment]
Hey @bnichs thanks for contributing, can you add translations for other languages via string resource? Even basic translation from google translate is okay and can be improved later on.

**Comment by bnichs** [comment]
Added the translations

**Comment by tien** [comment]
@bnichs The CI workflow can't build and give this error for some reason `FilterRulesScreen.kt:217:53 Unresolved reference 'not' for operator '!'`

**Comment by bnichs** [comment]
I've pushed a possible fix but im unable to kick off `create-test-build` to test it.

**Review by tien — APPROVED** [review]

**Pull request merged**
